- alias: "Update Simulated Power Sensors Every 10 Seconds"
  mode: single
  trigger:
    - platform: time_pattern
      seconds: "/10"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id:
          - sensor.building_a_pv_generation
          - sensor.building_a_floor1_left
          - sensor.building_a_floor1_right
          - sensor.building_a_grid_meter
          - sensor.building_b_pv_generation
          - sensor.building_b_floor1_left
          - sensor.building_b_floor1_right
          - sensor.building_b_floor2_left
          - sensor.building_b_floor2_right
          - sensor.building_b_grid_meter
          - sensor.building_c_pv_generation
          - sensor.building_c_floor1_left
          - sensor.building_c_floor1_right
          - sensor.building_c_floor2_left
          - sensor.building_c_floor2_right
          - sensor.building_c_floor3_left
          - sensor.building_c_floor3_right
          - sensor.building_c_grid_meter
          - sensor.building_d_pv_generation
          - sensor.building_d_floor1_left
          - sensor.building_d_floor1_right
          - sensor.building_d_floor2_left
          - sensor.building_d_floor2_right
          - sensor.building_d_floor3_left
          - sensor.building_d_floor3_right
          - sensor.building_d_floor4_left
          - sensor.building_d_floor4_right
          - sensor.building_d_floor5_left
          - sensor.building_d_floor5_right
          - sensor.building_d_grid_meter